# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[(1, b'create'), (2, b'delete'), (3, b'modify')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='items.Variant'),
        ),
    ]
