# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
