# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180722_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[(b'1', b'create'), (b'2', b'delete'), (b'3', b'modify')], max_length=1),
        ),
    ]
