# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180722_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
